import mongoose from "mongoose";
const { Schema } = mongoose;

// Define the main FoodLog Schema
const FoodLogSchema = new Schema({
  // _id is auto-generated by Mongoose by default.

  userId: {
    type: Schema.Types.ObjectId,
    ref: 'User', // This creates the reference to your User model
    required: true,
  },
  imageUrl: {
    type: String,
    required: true,
    // Typically a URL from an image hosting service like Cloudinary or S3
  },
  foodName: {
    type: String,
    required: true,
    trim: true,
  },
  portionSize: {
    type: String, // Use string to store units (e.g., "1 cup", "150g", "3 oz")
    required: true,
  },
  calories: {
    type: Number,
    required: true,
    min: 0, // Calories cannot be negative
  },
  protein: {
    type: Number,
    required: true,
    min: 0,
  },
  carbs: {
    type: Number,
    required: true,
    min: 0,
  },
  fats: {
    type: Number,
    required: true,
    min: 0,
  },
  fiber: {
    type: Number,
    required: true,
    min: 0,
  },
  confidence: {
    type: Number,
    required: true,
    min: 0,
    max: 1, // AI confidence score, typically between 0 (0%) and 1 (100%)
  },
  createdAt: {
    type: Date,
    default: Date.now,
    immutable: true,
  },
  mealType: {
    type: String,
    enum: ['breakfast', 'lunch', 'dinner', 'snack', 'other'], // Restrict to specific meal types
    required: false,
  },
});

// Create the Mongoose Model from the Schema
const FoodLog = mongoose.model('FoodLog', FoodLogSchema);

export default FoodLog;
